repository:
  name: discord
  owner: kolosys
  description: "![GoVersion](https://img.shields.io/badge/Go-1.24+-00ADD8?style=flat&logo=go)"
  import_path: github.com/kolosys/discord
  branch: main
  url: https://github.com/kolosys/discord
output:
  directory: /home/runner/work/discord/discord/docs
  clean: true
  preserve_custom: false
discovery:
  packages:
    auto_discover: true
    include_patterns:
      - ./...
    exclude_patterns:
      - ./vendor/...
      - ./test/...
      - ./.git/...
      - "**/*_test.go"
    skip_internal: true
    manual_packages: []
  api_generation:
    enabled: true
    include_unexported: false
    include_tests: false
    include_examples: true
  examples:
    enabled: true
    auto_discover: true
    directories: []
  benchmarks:
    enabled: false
    output_file: ""
    pattern: ""
    skip_empty_packages: false
templates:
  directory: ""
  custom_templates: []
metadata:
  version: latest
  go_version: "1.21"
  author: ""
  license: MIT
generation:
  date_format: "2006-01-02"
  include_generated_notice: true
  include_toc: true
  max_depth: 3
